URL_1 = "https://bonigarcia.dev/selenium-webdriver-java/data-types.html"

URL_2 = "https://bonigarcia.dev/selenium-webdriver-java/slow-calculator.html"
first_name = "Иван"
last_name = "Петров"
address = "Ленина, 55-3"
email = "test@skypro.com"
phone = "+7985899998787"
zip = ""
city = "Москва"
country = "Россия"
job_position = "QA"
company = "SkyPro"

URL_3 = "https://www.saucedemo.com/"